// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package kevm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hello struct {
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// A blockchain related configuration for the VM for the entire session.
	// Currently only Mantis-EVM is supported. Other VMs may ingore this
	// or may required different configurations.
	//
	// Types that are valid to be assigned to Config:
	//	*Hello_EthereumConfig
	//	*Hello_IeleConfig
	Config               isHello_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type isHello_Config interface {
	isHello_Config()
}

type Hello_EthereumConfig struct {
	EthereumConfig *EthereumConfig `protobuf:"bytes,2,opt,name=ethereumConfig,proto3,oneof"`
}

type Hello_IeleConfig struct {
	IeleConfig *IeleConfig `protobuf:"bytes,3,opt,name=ieleConfig,proto3,oneof"`
}

func (*Hello_EthereumConfig) isHello_Config() {}

func (*Hello_IeleConfig) isHello_Config() {}

func (m *Hello) GetConfig() isHello_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Hello) GetEthereumConfig() *EthereumConfig {
	if x, ok := m.GetConfig().(*Hello_EthereumConfig); ok {
		return x.EthereumConfig
	}
	return nil
}

func (m *Hello) GetIeleConfig() *IeleConfig {
	if x, ok := m.GetConfig().(*Hello_IeleConfig); ok {
		return x.IeleConfig
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Hello) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Hello_OneofMarshaler, _Hello_OneofUnmarshaler, _Hello_OneofSizer, []interface{}{
		(*Hello_EthereumConfig)(nil),
		(*Hello_IeleConfig)(nil),
	}
}

func _Hello_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Hello)
	// config
	switch x := m.Config.(type) {
	case *Hello_EthereumConfig:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EthereumConfig); err != nil {
			return err
		}
	case *Hello_IeleConfig:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IeleConfig); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Hello.Config has unexpected type %T", x)
	}
	return nil
}

func _Hello_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Hello)
	switch tag {
	case 2: // config.ethereumConfig
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EthereumConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Hello_EthereumConfig{msg}
		return true, err
	case 3: // config.ieleConfig
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IeleConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Hello_IeleConfig{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Hello_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Hello)
	// config
	switch x := m.Config.(type) {
	case *Hello_EthereumConfig:
		s := proto.Size(x.EthereumConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Hello_IeleConfig:
		s := proto.Size(x.IeleConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CallContext struct {
	CallerAddr []byte `protobuf:"bytes,1,opt,name=callerAddr,proto3" json:"callerAddr,omitempty"`
	// empty if contract creation
	RecipientAddr []byte       `protobuf:"bytes,2,opt,name=recipientAddr,proto3" json:"recipientAddr,omitempty"`
	InputData     []byte       `protobuf:"bytes,3,opt,name=inputData,proto3" json:"inputData,omitempty"`
	CallValue     []byte       `protobuf:"bytes,4,opt,name=callValue,proto3" json:"callValue,omitempty"`
	GasPrice      []byte       `protobuf:"bytes,5,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	GasProvided   []byte       `protobuf:"bytes,6,opt,name=gasProvided,proto3" json:"gasProvided,omitempty"`
	BlockHeader   *BlockHeader `protobuf:"bytes,7,opt,name=blockHeader,proto3" json:"blockHeader,omitempty"`
	// This may be used to override the VM configuration for the session. It used in tests to avoid
	// re-instantiating VM for each test.
	//
	// Types that are valid to be assigned to Config:
	//	*CallContext_EthereumConfig
	//	*CallContext_IeleConfig
	Config               isCallContext_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CallContext) Reset()         { *m = CallContext{} }
func (m *CallContext) String() string { return proto.CompactTextString(m) }
func (*CallContext) ProtoMessage()    {}
func (*CallContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *CallContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallContext.Unmarshal(m, b)
}
func (m *CallContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallContext.Marshal(b, m, deterministic)
}
func (m *CallContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallContext.Merge(m, src)
}
func (m *CallContext) XXX_Size() int {
	return xxx_messageInfo_CallContext.Size(m)
}
func (m *CallContext) XXX_DiscardUnknown() {
	xxx_messageInfo_CallContext.DiscardUnknown(m)
}

var xxx_messageInfo_CallContext proto.InternalMessageInfo

func (m *CallContext) GetCallerAddr() []byte {
	if m != nil {
		return m.CallerAddr
	}
	return nil
}

func (m *CallContext) GetRecipientAddr() []byte {
	if m != nil {
		return m.RecipientAddr
	}
	return nil
}

func (m *CallContext) GetInputData() []byte {
	if m != nil {
		return m.InputData
	}
	return nil
}

func (m *CallContext) GetCallValue() []byte {
	if m != nil {
		return m.CallValue
	}
	return nil
}

func (m *CallContext) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *CallContext) GetGasProvided() []byte {
	if m != nil {
		return m.GasProvided
	}
	return nil
}

func (m *CallContext) GetBlockHeader() *BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

type isCallContext_Config interface {
	isCallContext_Config()
}

type CallContext_EthereumConfig struct {
	EthereumConfig *EthereumConfig `protobuf:"bytes,8,opt,name=ethereumConfig,proto3,oneof"`
}

type CallContext_IeleConfig struct {
	IeleConfig *IeleConfig `protobuf:"bytes,9,opt,name=ieleConfig,proto3,oneof"`
}

func (*CallContext_EthereumConfig) isCallContext_Config() {}

func (*CallContext_IeleConfig) isCallContext_Config() {}

func (m *CallContext) GetConfig() isCallContext_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *CallContext) GetEthereumConfig() *EthereumConfig {
	if x, ok := m.GetConfig().(*CallContext_EthereumConfig); ok {
		return x.EthereumConfig
	}
	return nil
}

func (m *CallContext) GetIeleConfig() *IeleConfig {
	if x, ok := m.GetConfig().(*CallContext_IeleConfig); ok {
		return x.IeleConfig
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CallContext) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CallContext_OneofMarshaler, _CallContext_OneofUnmarshaler, _CallContext_OneofSizer, []interface{}{
		(*CallContext_EthereumConfig)(nil),
		(*CallContext_IeleConfig)(nil),
	}
}

func _CallContext_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CallContext)
	// config
	switch x := m.Config.(type) {
	case *CallContext_EthereumConfig:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EthereumConfig); err != nil {
			return err
		}
	case *CallContext_IeleConfig:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IeleConfig); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CallContext.Config has unexpected type %T", x)
	}
	return nil
}

func _CallContext_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CallContext)
	switch tag {
	case 8: // config.ethereumConfig
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EthereumConfig)
		err := b.DecodeMessage(msg)
		m.Config = &CallContext_EthereumConfig{msg}
		return true, err
	case 9: // config.ieleConfig
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IeleConfig)
		err := b.DecodeMessage(msg)
		m.Config = &CallContext_IeleConfig{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CallContext_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CallContext)
	// config
	switch x := m.Config.(type) {
	case *CallContext_EthereumConfig:
		s := proto.Size(x.EthereumConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CallContext_IeleConfig:
		s := proto.Size(x.IeleConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type BlockHeader struct {
	Beneficiary          []byte   `protobuf:"bytes,1,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	Difficulty           []byte   `protobuf:"bytes,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Number               []byte   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,4,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	UnixTimestamp        int64    `protobuf:"varint,5,opt,name=unixTimestamp,proto3" json:"unixTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetBeneficiary() []byte {
	if m != nil {
		return m.Beneficiary
	}
	return nil
}

func (m *BlockHeader) GetDifficulty() []byte {
	if m != nil {
		return m.Difficulty
	}
	return nil
}

func (m *BlockHeader) GetNumber() []byte {
	if m != nil {
		return m.Number
	}
	return nil
}

func (m *BlockHeader) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *BlockHeader) GetUnixTimestamp() int64 {
	if m != nil {
		return m.UnixTimestamp
	}
	return 0
}

type EthereumConfig struct {
	FrontierBlockNumber  []byte   `protobuf:"bytes,1,opt,name=frontierBlockNumber,proto3" json:"frontierBlockNumber,omitempty"`
	HomesteadBlockNumber []byte   `protobuf:"bytes,2,opt,name=homesteadBlockNumber,proto3" json:"homesteadBlockNumber,omitempty"`
	Eip150BlockNumber    []byte   `protobuf:"bytes,3,opt,name=eip150BlockNumber,proto3" json:"eip150BlockNumber,omitempty"`
	Eip160BlockNumber    []byte   `protobuf:"bytes,4,opt,name=eip160BlockNumber,proto3" json:"eip160BlockNumber,omitempty"`
	Eip161BlockNumber    []byte   `protobuf:"bytes,5,opt,name=eip161BlockNumber,proto3" json:"eip161BlockNumber,omitempty"`
	MaxCodeSize          []byte   `protobuf:"bytes,6,opt,name=maxCodeSize,proto3" json:"maxCodeSize,omitempty"`
	AccountStartNonce    []byte   `protobuf:"bytes,7,opt,name=accountStartNonce,proto3" json:"accountStartNonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EthereumConfig) Reset()         { *m = EthereumConfig{} }
func (m *EthereumConfig) String() string { return proto.CompactTextString(m) }
func (*EthereumConfig) ProtoMessage()    {}
func (*EthereumConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *EthereumConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EthereumConfig.Unmarshal(m, b)
}
func (m *EthereumConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EthereumConfig.Marshal(b, m, deterministic)
}
func (m *EthereumConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthereumConfig.Merge(m, src)
}
func (m *EthereumConfig) XXX_Size() int {
	return xxx_messageInfo_EthereumConfig.Size(m)
}
func (m *EthereumConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EthereumConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EthereumConfig proto.InternalMessageInfo

func (m *EthereumConfig) GetFrontierBlockNumber() []byte {
	if m != nil {
		return m.FrontierBlockNumber
	}
	return nil
}

func (m *EthereumConfig) GetHomesteadBlockNumber() []byte {
	if m != nil {
		return m.HomesteadBlockNumber
	}
	return nil
}

func (m *EthereumConfig) GetEip150BlockNumber() []byte {
	if m != nil {
		return m.Eip150BlockNumber
	}
	return nil
}

func (m *EthereumConfig) GetEip160BlockNumber() []byte {
	if m != nil {
		return m.Eip160BlockNumber
	}
	return nil
}

func (m *EthereumConfig) GetEip161BlockNumber() []byte {
	if m != nil {
		return m.Eip161BlockNumber
	}
	return nil
}

func (m *EthereumConfig) GetMaxCodeSize() []byte {
	if m != nil {
		return m.MaxCodeSize
	}
	return nil
}

func (m *EthereumConfig) GetAccountStartNonce() []byte {
	if m != nil {
		return m.AccountStartNonce
	}
	return nil
}

type IeleConfig struct {
	DanseBlockNumber     []byte   `protobuf:"bytes,1,opt,name=danseBlockNumber,proto3" json:"danseBlockNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IeleConfig) Reset()         { *m = IeleConfig{} }
func (m *IeleConfig) String() string { return proto.CompactTextString(m) }
func (*IeleConfig) ProtoMessage()    {}
func (*IeleConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *IeleConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IeleConfig.Unmarshal(m, b)
}
func (m *IeleConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IeleConfig.Marshal(b, m, deterministic)
}
func (m *IeleConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IeleConfig.Merge(m, src)
}
func (m *IeleConfig) XXX_Size() int {
	return xxx_messageInfo_IeleConfig.Size(m)
}
func (m *IeleConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IeleConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IeleConfig proto.InternalMessageInfo

func (m *IeleConfig) GetDanseBlockNumber() []byte {
	if m != nil {
		return m.DanseBlockNumber
	}
	return nil
}

type GetAccount struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccount) Reset()         { *m = GetAccount{} }
func (m *GetAccount) String() string { return proto.CompactTextString(m) }
func (*GetAccount) ProtoMessage()    {}
func (*GetAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *GetAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccount.Unmarshal(m, b)
}
func (m *GetAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccount.Marshal(b, m, deterministic)
}
func (m *GetAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccount.Merge(m, src)
}
func (m *GetAccount) XXX_Size() int {
	return xxx_messageInfo_GetAccount.Size(m)
}
func (m *GetAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccount.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccount proto.InternalMessageInfo

func (m *GetAccount) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type Account struct {
	// if account does not exist, nonce and balance will be empty
	// if account exists but is empty, nonce and balance will be equivalent to numeric zeroes
	Nonce                []byte   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Balance              []byte   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	CodeEmpty            bool     `protobuf:"varint,3,opt,name=codeEmpty,proto3" json:"codeEmpty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Account) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *Account) GetCodeEmpty() bool {
	if m != nil {
		return m.CodeEmpty
	}
	return false
}

type GetStorageData struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Offset               []byte   `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStorageData) Reset()         { *m = GetStorageData{} }
func (m *GetStorageData) String() string { return proto.CompactTextString(m) }
func (*GetStorageData) ProtoMessage()    {}
func (*GetStorageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *GetStorageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorageData.Unmarshal(m, b)
}
func (m *GetStorageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorageData.Marshal(b, m, deterministic)
}
func (m *GetStorageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorageData.Merge(m, src)
}
func (m *GetStorageData) XXX_Size() int {
	return xxx_messageInfo_GetStorageData.Size(m)
}
func (m *GetStorageData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorageData.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorageData proto.InternalMessageInfo

func (m *GetStorageData) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetStorageData) GetOffset() []byte {
	if m != nil {
		return m.Offset
	}
	return nil
}

type StorageData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageData) Reset()         { *m = StorageData{} }
func (m *StorageData) String() string { return proto.CompactTextString(m) }
func (*StorageData) ProtoMessage()    {}
func (*StorageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *StorageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageData.Unmarshal(m, b)
}
func (m *StorageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageData.Marshal(b, m, deterministic)
}
func (m *StorageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageData.Merge(m, src)
}
func (m *StorageData) XXX_Size() int {
	return xxx_messageInfo_StorageData.Size(m)
}
func (m *StorageData) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageData.DiscardUnknown(m)
}

var xxx_messageInfo_StorageData proto.InternalMessageInfo

func (m *StorageData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetCode struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCode) Reset()         { *m = GetCode{} }
func (m *GetCode) String() string { return proto.CompactTextString(m) }
func (*GetCode) ProtoMessage()    {}
func (*GetCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *GetCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCode.Unmarshal(m, b)
}
func (m *GetCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCode.Marshal(b, m, deterministic)
}
func (m *GetCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCode.Merge(m, src)
}
func (m *GetCode) XXX_Size() int {
	return xxx_messageInfo_GetCode.Size(m)
}
func (m *GetCode) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCode.DiscardUnknown(m)
}

var xxx_messageInfo_GetCode proto.InternalMessageInfo

func (m *GetCode) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type Code struct {
	Code                 []byte   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{10}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

type GetBlockhash struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockhash) Reset()         { *m = GetBlockhash{} }
func (m *GetBlockhash) String() string { return proto.CompactTextString(m) }
func (*GetBlockhash) ProtoMessage()    {}
func (*GetBlockhash) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{11}
}

func (m *GetBlockhash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockhash.Unmarshal(m, b)
}
func (m *GetBlockhash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockhash.Marshal(b, m, deterministic)
}
func (m *GetBlockhash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockhash.Merge(m, src)
}
func (m *GetBlockhash) XXX_Size() int {
	return xxx_messageInfo_GetBlockhash.Size(m)
}
func (m *GetBlockhash) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockhash.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockhash proto.InternalMessageInfo

func (m *GetBlockhash) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Blockhash struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blockhash) Reset()         { *m = Blockhash{} }
func (m *Blockhash) String() string { return proto.CompactTextString(m) }
func (*Blockhash) ProtoMessage()    {}
func (*Blockhash) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{12}
}

func (m *Blockhash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blockhash.Unmarshal(m, b)
}
func (m *Blockhash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blockhash.Marshal(b, m, deterministic)
}
func (m *Blockhash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blockhash.Merge(m, src)
}
func (m *Blockhash) XXX_Size() int {
	return xxx_messageInfo_Blockhash.Size(m)
}
func (m *Blockhash) XXX_DiscardUnknown() {
	xxx_messageInfo_Blockhash.DiscardUnknown(m)
}

var xxx_messageInfo_Blockhash proto.InternalMessageInfo

func (m *Blockhash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type CallResult struct {
	ReturnData []byte `protobuf:"bytes,1,opt,name=returnData,proto3" json:"returnData,omitempty"`
	// required for IELE VM
	ReturnCode       []byte             `protobuf:"bytes,2,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
	GasRemaining     []byte             `protobuf:"bytes,3,opt,name=gasRemaining,proto3" json:"gasRemaining,omitempty"`
	GasRefund        []byte             `protobuf:"bytes,4,opt,name=gasRefund,proto3" json:"gasRefund,omitempty"`
	Error            bool               `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	ModifiedAccounts []*ModifiedAccount `protobuf:"bytes,6,rep,name=modifiedAccounts,proto3" json:"modifiedAccounts,omitempty"`
	DeletedAccounts  [][]byte           `protobuf:"bytes,7,rep,name=deletedAccounts,proto3" json:"deletedAccounts,omitempty"`
	// touchedAccounts is specific Ethereum's EIP-161. VMs that do not follow these rules may ignore this field
	TouchedAccounts      [][]byte    `protobuf:"bytes,8,rep,name=touchedAccounts,proto3" json:"touchedAccounts,omitempty"`
	Logs                 []*LogEntry `protobuf:"bytes,9,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CallResult) Reset()         { *m = CallResult{} }
func (m *CallResult) String() string { return proto.CompactTextString(m) }
func (*CallResult) ProtoMessage()    {}
func (*CallResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{13}
}

func (m *CallResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResult.Unmarshal(m, b)
}
func (m *CallResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResult.Marshal(b, m, deterministic)
}
func (m *CallResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResult.Merge(m, src)
}
func (m *CallResult) XXX_Size() int {
	return xxx_messageInfo_CallResult.Size(m)
}
func (m *CallResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResult.DiscardUnknown(m)
}

var xxx_messageInfo_CallResult proto.InternalMessageInfo

func (m *CallResult) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

func (m *CallResult) GetReturnCode() []byte {
	if m != nil {
		return m.ReturnCode
	}
	return nil
}

func (m *CallResult) GetGasRemaining() []byte {
	if m != nil {
		return m.GasRemaining
	}
	return nil
}

func (m *CallResult) GetGasRefund() []byte {
	if m != nil {
		return m.GasRefund
	}
	return nil
}

func (m *CallResult) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *CallResult) GetModifiedAccounts() []*ModifiedAccount {
	if m != nil {
		return m.ModifiedAccounts
	}
	return nil
}

func (m *CallResult) GetDeletedAccounts() [][]byte {
	if m != nil {
		return m.DeletedAccounts
	}
	return nil
}

func (m *CallResult) GetTouchedAccounts() [][]byte {
	if m != nil {
		return m.TouchedAccounts
	}
	return nil
}

func (m *CallResult) GetLogs() []*LogEntry {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ModifiedAccount struct {
	Address        []byte           `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Nonce          []byte           `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Balance        []byte           `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	StorageUpdates []*StorageUpdate `protobuf:"bytes,4,rep,name=storageUpdates,proto3" json:"storageUpdates,omitempty"`
	// empty value indicates that no code has been assigned to this account
	Code                 []byte   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifiedAccount) Reset()         { *m = ModifiedAccount{} }
func (m *ModifiedAccount) String() string { return proto.CompactTextString(m) }
func (*ModifiedAccount) ProtoMessage()    {}
func (*ModifiedAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{14}
}

func (m *ModifiedAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifiedAccount.Unmarshal(m, b)
}
func (m *ModifiedAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifiedAccount.Marshal(b, m, deterministic)
}
func (m *ModifiedAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifiedAccount.Merge(m, src)
}
func (m *ModifiedAccount) XXX_Size() int {
	return xxx_messageInfo_ModifiedAccount.Size(m)
}
func (m *ModifiedAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifiedAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ModifiedAccount proto.InternalMessageInfo

func (m *ModifiedAccount) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ModifiedAccount) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *ModifiedAccount) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *ModifiedAccount) GetStorageUpdates() []*StorageUpdate {
	if m != nil {
		return m.StorageUpdates
	}
	return nil
}

func (m *ModifiedAccount) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

type StorageUpdate struct {
	Offset               []byte   `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageUpdate) Reset()         { *m = StorageUpdate{} }
func (m *StorageUpdate) String() string { return proto.CompactTextString(m) }
func (*StorageUpdate) ProtoMessage()    {}
func (*StorageUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{15}
}

func (m *StorageUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageUpdate.Unmarshal(m, b)
}
func (m *StorageUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageUpdate.Marshal(b, m, deterministic)
}
func (m *StorageUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageUpdate.Merge(m, src)
}
func (m *StorageUpdate) XXX_Size() int {
	return xxx_messageInfo_StorageUpdate.Size(m)
}
func (m *StorageUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_StorageUpdate proto.InternalMessageInfo

func (m *StorageUpdate) GetOffset() []byte {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *StorageUpdate) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LogEntry struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics               [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{16}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *LogEntry) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *LogEntry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type VMQuery struct {
	// Types that are valid to be assigned to Query:
	//	*VMQuery_GetAccount
	//	*VMQuery_GetStorageData
	//	*VMQuery_GetCode
	//	*VMQuery_GetBlockhash
	//	*VMQuery_CallResult
	Query                isVMQuery_Query `protobuf_oneof:"query"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VMQuery) Reset()         { *m = VMQuery{} }
func (m *VMQuery) String() string { return proto.CompactTextString(m) }
func (*VMQuery) ProtoMessage()    {}
func (*VMQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{17}
}

func (m *VMQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VMQuery.Unmarshal(m, b)
}
func (m *VMQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VMQuery.Marshal(b, m, deterministic)
}
func (m *VMQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VMQuery.Merge(m, src)
}
func (m *VMQuery) XXX_Size() int {
	return xxx_messageInfo_VMQuery.Size(m)
}
func (m *VMQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_VMQuery.DiscardUnknown(m)
}

var xxx_messageInfo_VMQuery proto.InternalMessageInfo

type isVMQuery_Query interface {
	isVMQuery_Query()
}

type VMQuery_GetAccount struct {
	GetAccount *GetAccount `protobuf:"bytes,1,opt,name=getAccount,proto3,oneof"`
}

type VMQuery_GetStorageData struct {
	GetStorageData *GetStorageData `protobuf:"bytes,2,opt,name=getStorageData,proto3,oneof"`
}

type VMQuery_GetCode struct {
	GetCode *GetCode `protobuf:"bytes,3,opt,name=getCode,proto3,oneof"`
}

type VMQuery_GetBlockhash struct {
	GetBlockhash *GetBlockhash `protobuf:"bytes,4,opt,name=getBlockhash,proto3,oneof"`
}

type VMQuery_CallResult struct {
	CallResult *CallResult `protobuf:"bytes,5,opt,name=callResult,proto3,oneof"`
}

func (*VMQuery_GetAccount) isVMQuery_Query() {}

func (*VMQuery_GetStorageData) isVMQuery_Query() {}

func (*VMQuery_GetCode) isVMQuery_Query() {}

func (*VMQuery_GetBlockhash) isVMQuery_Query() {}

func (*VMQuery_CallResult) isVMQuery_Query() {}

func (m *VMQuery) GetQuery() isVMQuery_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *VMQuery) GetGetAccount() *GetAccount {
	if x, ok := m.GetQuery().(*VMQuery_GetAccount); ok {
		return x.GetAccount
	}
	return nil
}

func (m *VMQuery) GetGetStorageData() *GetStorageData {
	if x, ok := m.GetQuery().(*VMQuery_GetStorageData); ok {
		return x.GetStorageData
	}
	return nil
}

func (m *VMQuery) GetGetCode() *GetCode {
	if x, ok := m.GetQuery().(*VMQuery_GetCode); ok {
		return x.GetCode
	}
	return nil
}

func (m *VMQuery) GetGetBlockhash() *GetBlockhash {
	if x, ok := m.GetQuery().(*VMQuery_GetBlockhash); ok {
		return x.GetBlockhash
	}
	return nil
}

func (m *VMQuery) GetCallResult() *CallResult {
	if x, ok := m.GetQuery().(*VMQuery_CallResult); ok {
		return x.CallResult
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*VMQuery) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _VMQuery_OneofMarshaler, _VMQuery_OneofUnmarshaler, _VMQuery_OneofSizer, []interface{}{
		(*VMQuery_GetAccount)(nil),
		(*VMQuery_GetStorageData)(nil),
		(*VMQuery_GetCode)(nil),
		(*VMQuery_GetBlockhash)(nil),
		(*VMQuery_CallResult)(nil),
	}
}

func _VMQuery_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*VMQuery)
	// query
	switch x := m.Query.(type) {
	case *VMQuery_GetAccount:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetAccount); err != nil {
			return err
		}
	case *VMQuery_GetStorageData:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetStorageData); err != nil {
			return err
		}
	case *VMQuery_GetCode:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetCode); err != nil {
			return err
		}
	case *VMQuery_GetBlockhash:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetBlockhash); err != nil {
			return err
		}
	case *VMQuery_CallResult:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CallResult); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("VMQuery.Query has unexpected type %T", x)
	}
	return nil
}

func _VMQuery_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*VMQuery)
	switch tag {
	case 1: // query.getAccount
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetAccount)
		err := b.DecodeMessage(msg)
		m.Query = &VMQuery_GetAccount{msg}
		return true, err
	case 2: // query.getStorageData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetStorageData)
		err := b.DecodeMessage(msg)
		m.Query = &VMQuery_GetStorageData{msg}
		return true, err
	case 3: // query.getCode
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetCode)
		err := b.DecodeMessage(msg)
		m.Query = &VMQuery_GetCode{msg}
		return true, err
	case 4: // query.getBlockhash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetBlockhash)
		err := b.DecodeMessage(msg)
		m.Query = &VMQuery_GetBlockhash{msg}
		return true, err
	case 5: // query.callResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CallResult)
		err := b.DecodeMessage(msg)
		m.Query = &VMQuery_CallResult{msg}
		return true, err
	default:
		return false, nil
	}
}

func _VMQuery_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*VMQuery)
	// query
	switch x := m.Query.(type) {
	case *VMQuery_GetAccount:
		s := proto.Size(x.GetAccount)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *VMQuery_GetStorageData:
		s := proto.Size(x.GetStorageData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *VMQuery_GetCode:
		s := proto.Size(x.GetCode)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *VMQuery_GetBlockhash:
		s := proto.Size(x.GetBlockhash)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *VMQuery_CallResult:
		s := proto.Size(x.CallResult)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Hello)(nil), "io.iohk.ethereum.extvm.Hello")
	proto.RegisterType((*CallContext)(nil), "io.iohk.ethereum.extvm.CallContext")
	proto.RegisterType((*BlockHeader)(nil), "io.iohk.ethereum.extvm.BlockHeader")
	proto.RegisterType((*EthereumConfig)(nil), "io.iohk.ethereum.extvm.EthereumConfig")
	proto.RegisterType((*IeleConfig)(nil), "io.iohk.ethereum.extvm.IeleConfig")
	proto.RegisterType((*GetAccount)(nil), "io.iohk.ethereum.extvm.GetAccount")
	proto.RegisterType((*Account)(nil), "io.iohk.ethereum.extvm.Account")
	proto.RegisterType((*GetStorageData)(nil), "io.iohk.ethereum.extvm.GetStorageData")
	proto.RegisterType((*StorageData)(nil), "io.iohk.ethereum.extvm.StorageData")
	proto.RegisterType((*GetCode)(nil), "io.iohk.ethereum.extvm.GetCode")
	proto.RegisterType((*Code)(nil), "io.iohk.ethereum.extvm.Code")
	proto.RegisterType((*GetBlockhash)(nil), "io.iohk.ethereum.extvm.GetBlockhash")
	proto.RegisterType((*Blockhash)(nil), "io.iohk.ethereum.extvm.Blockhash")
	proto.RegisterType((*CallResult)(nil), "io.iohk.ethereum.extvm.CallResult")
	proto.RegisterType((*ModifiedAccount)(nil), "io.iohk.ethereum.extvm.ModifiedAccount")
	proto.RegisterType((*StorageUpdate)(nil), "io.iohk.ethereum.extvm.StorageUpdate")
	proto.RegisterType((*LogEntry)(nil), "io.iohk.ethereum.extvm.LogEntry")
	proto.RegisterType((*VMQuery)(nil), "io.iohk.ethereum.extvm.VMQuery")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 1001 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x8e, 0x1b, 0x45,
	0x10, 0x5e, 0xff, 0xdb, 0x65, 0x67, 0x13, 0x9a, 0x28, 0x1a, 0x45, 0x88, 0x98, 0x49, 0x58, 0x2c,
	0x84, 0xac, 0x64, 0x81, 0x08, 0x29, 0xa7, 0x78, 0x77, 0xb5, 0x06, 0x65, 0xa3, 0x65, 0x0c, 0x41,
	0xe2, 0xd6, 0x9e, 0x29, 0x8f, 0x5b, 0x3b, 0x33, 0x6d, 0x7a, 0x7a, 0x56, 0x6b, 0xae, 0x3c, 0x0d,
	0x2f, 0xc0, 0x91, 0x0b, 0x2f, 0xc0, 0xeb, 0x70, 0x43, 0xdd, 0xf3, 0xd7, 0xe3, 0x3f, 0x0e, 0xe4,
	0xe4, 0xa9, 0xaf, 0xbe, 0xfa, 0x5c, 0x53, 0x55, 0x5d, 0x3d, 0xd0, 0x0b, 0x63, 0x7f, 0xbc, 0x12,
	0x5c, 0x72, 0xf2, 0x88, 0xf1, 0x31, 0xe3, 0xcb, 0x9b, 0x31, 0xca, 0x25, 0x0a, 0x4c, 0xc2, 0x31,
	0xde, 0xc9, 0xdb, 0xd0, 0xfe, 0xab, 0x06, 0xad, 0x29, 0x06, 0x01, 0x27, 0x16, 0x74, 0x6e, 0x51,
	0xc4, 0x8c, 0x47, 0x56, 0x6d, 0x58, 0x1b, 0xf5, 0x9c, 0xdc, 0x24, 0xd7, 0x70, 0x9c, 0x47, 0x9d,
	0xf1, 0x68, 0xc1, 0x7c, 0xab, 0x3e, 0xac, 0x8d, 0xfa, 0xa7, 0x27, 0xe3, 0xdd, 0xa2, 0xe3, 0x8b,
	0x0a, 0x7b, 0x7a, 0xe4, 0x6c, 0xc4, 0x93, 0x73, 0x00, 0x86, 0x01, 0x66, 0x6a, 0x0d, 0xad, 0x66,
	0xef, 0x53, 0xfb, 0xb6, 0x60, 0x4e, 0x8f, 0x1c, 0x23, 0x6e, 0xd2, 0x85, 0xb6, 0xab, 0x9f, 0xec,
	0x3f, 0x1a, 0xd0, 0x3f, 0xa3, 0x41, 0x70, 0xc6, 0x23, 0x89, 0x77, 0x92, 0x7c, 0x0c, 0xe0, 0xd2,
	0x20, 0x40, 0xf1, 0xda, 0xf3, 0x84, 0x7e, 0x9d, 0x81, 0x63, 0x20, 0xe4, 0x19, 0xdc, 0x13, 0xe8,
	0xb2, 0x15, 0xc3, 0x48, 0x6a, 0x4a, 0x5d, 0x53, 0xaa, 0x20, 0xf9, 0x08, 0x7a, 0x2c, 0x5a, 0x25,
	0xf2, 0x9c, 0x4a, 0xaa, 0x93, 0x1c, 0x38, 0x25, 0xa0, 0xbc, 0x4a, 0xf1, 0x1d, 0x0d, 0x12, 0xb4,
	0x9a, 0xa9, 0xb7, 0x00, 0xc8, 0x63, 0xe8, 0xfa, 0x34, 0xbe, 0x16, 0xcc, 0x45, 0xab, 0xa5, 0x9d,
	0x85, 0x4d, 0x86, 0xd0, 0xd7, 0xcf, 0xfc, 0x96, 0x79, 0xe8, 0x59, 0x6d, 0xed, 0x36, 0x21, 0x72,
	0x01, 0xfd, 0x79, 0xc0, 0xdd, 0x9b, 0x29, 0x52, 0x0f, 0x85, 0xd5, 0xd1, 0x05, 0x7a, 0xba, 0xaf,
	0x40, 0x93, 0x92, 0xea, 0x98, 0x71, 0x3b, 0x1a, 0xd7, 0x7d, 0xaf, 0x8d, 0xeb, 0xfd, 0xef, 0xc6,
	0xfd, 0x5e, 0x83, 0xbe, 0x91, 0xbe, 0x2a, 0xcd, 0x1c, 0x23, 0x5c, 0x30, 0x97, 0x51, 0xb1, 0xce,
	0x3a, 0x67, 0x42, 0xaa, 0xb5, 0x1e, 0x5b, 0x2c, 0x98, 0x9b, 0x04, 0x72, 0x9d, 0xf5, 0xcd, 0x40,
	0xc8, 0x23, 0x68, 0x47, 0x49, 0x38, 0x47, 0x91, 0x75, 0x2c, 0xb3, 0xb2, 0x86, 0xbc, 0x61, 0x21,
	0x93, 0x59, 0xb7, 0x0a, 0x5b, 0x8d, 0x43, 0x12, 0xb1, 0xbb, 0x1f, 0x58, 0x88, 0xb1, 0xa4, 0xe1,
	0x4a, 0x77, 0xac, 0xe1, 0x54, 0x41, 0xfb, 0xef, 0x3a, 0x1c, 0x57, 0x0b, 0x44, 0x9e, 0xc3, 0x87,
	0x0b, 0xc1, 0x23, 0xc9, 0x50, 0xe8, 0xb7, 0x78, 0x9b, 0xfe, 0x73, 0x9a, 0xf6, 0x2e, 0x17, 0x39,
	0x85, 0x87, 0x4b, 0xae, 0x14, 0x91, 0x7a, 0x66, 0x48, 0xfa, 0x22, 0x3b, 0x7d, 0xe4, 0x0b, 0xf8,
	0x00, 0xd9, 0xea, 0xc5, 0xd7, 0xcf, 0xcd, 0x80, 0xf4, 0xed, 0xb6, 0x1d, 0x39, 0xfb, 0x65, 0x85,
	0xdd, 0x2c, 0xd9, 0x2f, 0x77, 0xb2, 0x5f, 0x98, 0xec, 0x96, 0xc1, 0x36, 0x1d, 0xaa, 0x3d, 0x21,
	0xbd, 0x3b, 0xe3, 0x1e, 0xce, 0xd8, 0xaf, 0x98, 0x4f, 0xae, 0x01, 0x29, 0x3d, 0xea, 0xba, 0x3c,
	0x89, 0xe4, 0x4c, 0x52, 0x21, 0xdf, 0xf2, 0xc8, 0x45, 0x3d, 0xbf, 0x03, 0x67, 0xdb, 0x61, 0x7f,
	0x03, 0x50, 0x0e, 0x09, 0xf9, 0x1c, 0x1e, 0x78, 0x34, 0x8a, 0x71, 0xbb, 0x94, 0x5b, 0xb8, 0x7d,
	0x02, 0x70, 0x89, 0xf2, 0x75, 0xaa, 0xa8, 0x76, 0x17, 0xf5, 0x3c, 0x81, 0x71, 0x9c, 0x05, 0xe4,
	0xa6, 0xfd, 0x13, 0x74, 0x72, 0xd2, 0x43, 0x68, 0x45, 0x3a, 0x9d, 0x94, 0x92, 0x1a, 0x2a, 0x74,
	0x4e, 0x03, 0xaa, 0xf0, 0xb4, 0x07, 0xb9, 0xa9, 0x0f, 0x38, 0xf7, 0xf0, 0x22, 0x5c, 0xc9, 0xb5,
	0x2e, 0x77, 0xd7, 0x29, 0x01, 0x7b, 0x02, 0xc7, 0x97, 0x28, 0x67, 0x92, 0x0b, 0xea, 0xa3, 0x5e,
	0x08, 0x7b, 0x93, 0x50, 0x33, 0xc9, 0x17, 0x8b, 0x18, 0x65, 0xf6, 0x17, 0x99, 0x65, 0x7f, 0x02,
	0x7d, 0x53, 0x80, 0x40, 0xd3, 0x53, 0xab, 0x26, 0x8d, 0xd6, 0xcf, 0xf6, 0x53, 0xe8, 0x5c, 0xa2,
	0x54, 0xe5, 0x3d, 0xf0, 0x92, 0x8f, 0xa1, 0xa9, 0x19, 0x04, 0x9a, 0x2a, 0xc1, 0x5c, 0x40, 0x3d,
	0xdb, 0x27, 0x30, 0xb8, 0x44, 0xa9, 0x4b, 0xb7, 0xa4, 0xf1, 0xd2, 0xc8, 0x45, 0xb1, 0x5a, 0x45,
	0x2e, 0x4f, 0xa0, 0x57, 0x92, 0x08, 0x34, 0xd5, 0x6f, 0x2e, 0xa4, 0x9e, 0xed, 0xdf, 0x1a, 0x00,
	0x6a, 0xc7, 0x3a, 0x18, 0x27, 0x81, 0x5e, 0xb1, 0x02, 0x65, 0x22, 0xa2, 0xf3, 0x32, 0x65, 0x03,
	0x29, 0xfd, 0x2a, 0xb3, 0xfc, 0x9c, 0x96, 0x08, 0xb1, 0x61, 0xe0, 0xd3, 0xd8, 0xc1, 0x90, 0xb2,
	0x88, 0x45, 0x7e, 0x36, 0xcf, 0x15, 0x4c, 0x75, 0x40, 0xdb, 0x8b, 0x24, 0xf2, 0xf2, 0x15, 0x5b,
	0x00, 0xaa, 0x9f, 0x28, 0x04, 0x4f, 0xc7, 0xb5, 0xeb, 0xa4, 0x06, 0x99, 0xc1, 0x83, 0x90, 0x7b,
	0x6c, 0xc1, 0xd0, 0xcb, 0x1a, 0x1f, 0x5b, 0xed, 0x61, 0x63, 0xd4, 0x3f, 0xfd, 0x6c, 0xdf, 0x9e,
	0xba, 0xaa, 0xf2, 0x9d, 0x2d, 0x01, 0x32, 0x82, 0xfb, 0x1e, 0x06, 0x28, 0x0d, 0xcd, 0xce, 0xb0,
	0x31, 0x1a, 0x38, 0x9b, 0xb0, 0x62, 0x4a, 0x9e, 0xb8, 0x4b, 0x83, 0xd9, 0x4d, 0x99, 0x1b, 0x30,
	0xf9, 0x0a, 0x9a, 0x01, 0xf7, 0x63, 0xab, 0xa7, 0x93, 0x1b, 0xee, 0x4b, 0xee, 0x0d, 0xf7, 0x2f,
	0x22, 0x29, 0xd6, 0x8e, 0x66, 0xdb, 0x7f, 0xd6, 0xe0, 0xfe, 0x46, 0xbe, 0x07, 0x06, 0xaf, 0x18,
	0xf9, 0xfa, 0x9e, 0x91, 0x6f, 0x54, 0x47, 0xfe, 0x0a, 0x8e, 0xe3, 0x74, 0x20, 0x7f, 0x5c, 0x79,
	0x54, 0x62, 0x6c, 0x35, 0x75, 0x76, 0x9f, 0xee, 0xcb, 0x6e, 0x66, 0xb2, 0x9d, 0x8d, 0xe0, 0x62,
	0x1e, 0x5b, 0xc6, 0x3c, 0xbe, 0x82, 0x7b, 0x95, 0xa0, 0x8d, 0x81, 0x2c, 0x0e, 0x47, 0x71, 0x1a,
	0xea, 0xc6, 0x69, 0xb8, 0x86, 0x6e, 0x5e, 0x8f, 0xc3, 0xc7, 0x4d, 0xf2, 0x15, 0x73, 0x63, 0xab,
	0xae, 0x4b, 0x9f, 0x59, 0x85, 0x62, 0xc3, 0x50, 0xfc, 0xa7, 0x0e, 0x9d, 0x77, 0x57, 0xdf, 0x27,
	0x28, 0xd6, 0xea, 0x72, 0xf3, 0x8b, 0x9d, 0xa2, 0x45, 0x0f, 0x5c, 0x6e, 0xe5, 0xf6, 0x51, 0x97,
	0x5b, 0x19, 0xa7, 0x2e, 0x5d, 0xbf, 0xb2, 0x18, 0xfe, 0xeb, 0x6b, 0xa9, 0xba, 0x46, 0xd4, 0xa5,
	0x5b, 0x8d, 0x27, 0xaf, 0xa0, 0xe3, 0xa7, 0x3b, 0x20, 0xfb, 0x54, 0x7a, 0x72, 0x40, 0x4a, 0xd1,
	0xa6, 0x47, 0x4e, 0x1e, 0x41, 0xbe, 0x83, 0x81, 0x6f, 0x9c, 0x7f, 0x7d, 0x8c, 0xfa, 0xa7, 0xcf,
	0x0e, 0x28, 0x14, 0xdc, 0xe9, 0x91, 0x53, 0x89, 0x55, 0x05, 0x72, 0x8b, 0x0d, 0xa0, 0xbb, 0x7a,
	0xa0, 0x40, 0xe5, 0xae, 0x50, 0x05, 0x2a, 0xe3, 0x26, 0x1d, 0x68, 0xfd, 0xa2, 0xea, 0x3d, 0x69,
	0xff, 0xdc, 0xbc, 0xc1, 0xdb, 0x70, 0xde, 0xd6, 0x9f, 0xa8, 0x5f, 0xfe, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x01, 0x37, 0x90, 0x96, 0xaf, 0x0a, 0x00, 0x00,
}
